version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/app/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/mysql/logs:/var/log/mysql
      - ./volumes/mysql/data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      UPLOAD_LIMIT: 500M
      UPLOAD_MAX_FILESIZE: 500M
      PMA_ARBITRARY: 1
    ports:
      - "9000:80"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
